config/routes.rb
Rails.application.routes.draw do
  # Authentication
  use_doorkeeper
  devise_for :users, :skip => [:passwords, :registrations]
    as :user do
      namespace :user do
        patch 'update'
        get 'edit'
      end
      scope '/admin' do
        resources :user, :controller => 'user_admin'
        get 'impersonate_user', :controller => 'user_admin'
        post 'halt_impersonate_user', :controller => 'user_admin'
      end
    end

  # Pages
  get 'arrival_schedule/index'
  get 'arrival_schedule/check_location_test'
  get 'pages/auth_success'
  get 'notifications/index'

  # Pages API
  post 'arrival_schedule/locations'
  post 'arrival_schedule/schedule'
  post 'arrival_schedule/remove_schedule'
  post 'arrival_schedule/check_location'
  post 'arrival_schedule/process_locations'
  post 'location_check/location_checks'
  post 'location_check/find_location'

  # API
  namespace :api do
    namespace :v1 do
      post 'arrival_schedule/check_location'
      post 'arrival_schedule/process_locations'
      post 'arrival_schedule/active_locations'
    end
  end

  # Site root
  root 'arrival_schedule#index'
end

app/controllers/user_admin_controller.rb
class UserAdminController < ApplicationController
  before_filter :authenticate_user!, :check_admin!, except: [:halt_impersonate_user]
  before_filter :authenticate_user!, :check_non_impersonation_admin!, only: [:halt_impersonate_user]

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Created user number #{@user.id}"
      redirect_to user_index_path
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    params[:user].delete(:password) if params[:user][:password].blank?

    if @user.update_attributes(user_params)
      flash[:success] = "Updated user number #{@user.id}"
      redirect_to user_index_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      flash[:success] = "Deleted user number #{@user.id}"
    else
      flash[:success] = "Could not delete user number #{@user.id}"
    end

    redirect_to user_index_path
  end

  def impersonate_user
    session[:impersonation_user_id] = params[:user_id]
    redirect_to '/'
  end

  def halt_impersonate_user
    session[:impersonation_user_id] = nil
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :display_name)
  end

  def check_admin!
    render text: "You are not authorized for this action!", status: :unauthorized unless current_user.admin?
  end

  def check_non_impersonation_admin!
    render text: "You are not authorized for this action!", status: :unauthorized unless devise_current_user.admin?
  end

end

app/views/user_admin/edit.html.haml
.container-fluid.edit-user-content
  .row
    .col-md-12
      .jumbotron
        .field
          %h1 Edit User Information
        .edit-entry
          - if @user && @user.errors.keys.length > 0
            %div{class: 'alert alert-danger'}
              Please fix the following errors:
              %ul.error-list
                - @user.errors.each do |k,v|
                  %li= v
          = form_for(@user, role: 'form') do |f|
            .form-group
              = f.label :email
              %br
              = f.email_field :email, autofocus: true, placeholder: 'Email', class: 'form-control edit-user-input'
            .form-group
              = f.label :display_name
              %br
              = f.text_field :display_name, placeholder: 'Display name (optional)', class: 'form-control edit-user-input'
            .form-group
              = f.label :new_password
              %br
              = f.password_field :password, autocomplete: "off", placeholder: 'Password', class: 'form-control edit-user-input'
            .form-group.field
              = f.submit "Update", class: 'btn btn-default btn-large'
            .form-group.field
              = link_to "cancel", user_index_path, class: 'btn btn-link'

app/views/user_admin/index.html.haml
.container-fluid.edit-user-content
  .row
    .col-md-12
      .jumbotron
        - if flash[:success]
          = content_tag :div, flash[:success], class: 'alert alert-success'
        .field
          %h1 User Management
        .table-responsive
          %table{class: 'table table-striped'}
            %thead
              %tr.table-header
                %th ID
                %th Email
                %th
                %th
            %tbody
              - @users.each do |user|
                %tr
                  %td= user.id
                  %td= link_to user.email, edit_user_path(user)
                  %td= link_to image_tag("delete.png", border: "0"), user, :method=>'delete'
                  %td= link_to 'impersonate', impersonate_user_path(user_id: user.id)
        .field
          = link_to "New User", new_user_path, class: 'btn btn-default btn-large'
        .field
          = link_to "cancel", root_path, class: 'btn btn-link'

app/views/user_admin/new.html.haml
.container-fluid.edit-user-content
  .row
    .col-md-12
      .jumbotron
        .field
          %h1 Create New User
        .edit-entry
          - if @user && @user.errors.keys.length > 0
            %div{class: 'alert alert-danger'}
              Please fix the following errors:
              %ul.error-list
                - @user.errors.each do |k,v|
                  %li= v
          = form_for(:user, url: user_index_path, role: 'form') do |f|
            .form-group
              = f.label :email
              %br
              = f.email_field :email, autofocus: true, placeholder: 'Email', class: 'form-control edit-user-input'
            .form-group
              = f.label :display_name
              %br
              = f.text_field :display_name, placeholder: 'Display name (optional)', class: 'form-control edit-user-input'
            .form-group
              = f.label :new_password
              %br
              = f.password_field :password, autocomplete: "off", placeholder: 'Password', class: 'form-control edit-user-input'
            .form-group.field
              = f.submit "Create", class: 'btn btn-default btn-large'
            .form-group.field
              = link_to "cancel", user_index_path, class: 'btn btn-link'