config/routes.rb
Rails.application.routes.draw do
  # Authentication
  use_doorkeeper
  devise_for :users, :skip => [:passwords, :registrations]
    as :user do
      namespace :user do
        patch 'update'
        get 'edit'
      end
      scope '/admin' do
        resources :user, :controller => 'user_admin'
        get 'impersonate_user', :controller => 'user_admin'
        post 'halt_impersonate_user', :controller => 'user_admin'
      end
    end

  # Pages
  get 'arrival_schedule/index'
  get 'arrival_schedule/check_location_test'
  get 'pages/auth_success'
  get 'notifications/index'

  # Pages API
  post 'arrival_schedule/locations'
  post 'arrival_schedule/schedule'
  post 'arrival_schedule/remove_schedule'
  post 'arrival_schedule/check_location'
  post 'arrival_schedule/process_locations'
  post 'location_check/location_checks'
  post 'location_check/find_location'

  # API
  namespace :api do
    namespace :v1 do
      post 'arrival_schedule/check_location'
      post 'arrival_schedule/process_locations'
      post 'arrival_schedule/active_locations'
    end
  end

  # Site root
  root 'arrival_schedule#index'
end

app/views/shared/_admin_nav.html.haml
- if user_signed_in? && current_user.admin?
  .admin-nav-wrapper
    .nav
      = link_to 'Users', user_index_path
      #{'|'}
      = link_to 'Testing', arrival_schedule_check_location_test_path
      #{'|'}
      = link_to 'Advanced', arrival_schedule_index_path(radius: 1)
      #{'|'}
      = link_to 'OAuth', oauth_applications_path
      #{'|'}
      = link_to 'Recent Location Checks', notifications_index_path

app/views/shared/_nav.html.haml
- if user_signed_in?
  .nav-wrapper
    .nav
      = link_to current_user.email, user_edit_path
      #{'|'}
      = link_to 'preferences', user_edit_path
      #{'|'}
      %div{style: 'white-space: nowrap; display: inline-block'}
        - if impersonating?
          = link_to "halt impersonation", halt_impersonate_user_path, :method => 'post'
        - else
          = link_to "sign out", destroy_user_session_path, :method=>'delete'