config/routes.rb
Rails.application.routes.draw do
  # Authentication
  use_doorkeeper
  devise_for :users, :skip => [:passwords, :registrations]
    as :user do
      namespace :user do
        patch 'update'
        get 'edit'
      end
      scope '/admin' do
        resources :user, :controller => 'user_admin'
        get 'impersonate_user', :controller => 'user_admin'
        post 'halt_impersonate_user', :controller => 'user_admin'
      end
    end

  # Pages
  get 'arrival_schedule/index'
  get 'arrival_schedule/check_location_test'
  get 'pages/auth_success'
  get 'notifications/index'

  # Pages API
  post 'arrival_schedule/locations'
  post 'arrival_schedule/schedule'
  post 'arrival_schedule/remove_schedule'
  post 'arrival_schedule/check_location'
  post 'arrival_schedule/process_locations'
  post 'location_check/location_checks'
  post 'location_check/find_location'

  # API
  namespace :api do
    namespace :v1 do
      post 'arrival_schedule/check_location'
      post 'arrival_schedule/process_locations'
      post 'arrival_schedule/active_locations'
    end
  end

  # Site root
  root 'arrival_schedule#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!

  def edit
    @user   = current_user
    @errors = []
  end

  def update
    @user   = User.find(current_user.id)
    @errors = []

    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
      params[:user].delete(:current_password)
    elsif !@user.valid_password?(params[:user][:current_password])
      @errors = [t('activerecord.errors.models.user.attributes.current_password.invalid')]
      render 'edit'
      return
    end

    if @user.update_attributes(user_params)
      sign_in @user, bypass: true
      redirect_to '/'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :display_name)
  end

end

app/views/user/edit.html.haml
.container-fluid.edit-user-content
  .row
    .col-md-12
      .jumbotron.edit-entry
        .field
          %h1 Edit User Information
        - if @user && (@user.errors.keys.length > 0 || @errors.length > 0)
          %div{class: 'alert alert-danger'}
            Please fix the following errors:
            %ul.error-list
              - @user.errors.each do |k,v|
                %li= v
              - @errors.each do |e|
                %li= e
        = form_for(@user, url: user_update_path, role: 'form') do |f|
          .form-group
            = f.label :email
            %br
            = f.email_field :email, autofocus: true, placeholder: 'Email', class: 'form-control edit-user-input'
          .form-group
            = f.label :display_name
            %br
            = f.text_field :display_name, placeholder: 'Display name (optional)', class: 'form-control edit-user-input'
          .form-group
            = f.label :current_password
            %br
            = f.password_field :current_password, autocomplete: "off", placeholder: 'Password', class: 'form-control edit-user-input'
          .form-group
            = f.label :new_password
            %br
            = f.password_field :password, autocomplete: "off", placeholder: 'Password', class: 'form-control edit-user-input'
          .form-group
            = f.label :new_password_confirmation
            %br
            = f.password_field :password_confirmation, autocomplete: "off", placeholder: 'Password', class: 'form-control edit-user-input'
          .form-group.field
            = f.submit "Update", class: 'btn btn-default btn-large'
          .form-group.field
            = link_to "cancel", root_path, class: 'btn btn-link'